#!/bin/sh
# $Id: mpirun,v 1.1.6.1 2002/04/24 03:26:00 erik Exp $
if [ $1 !=  "-np" ]; then
progname=$*
elif  [ $2 =  "1" ]; then
shift ; shift
progname=$*
else
echo "FAIL:Uniprocessor version of MPI can only use one processor."
exit 1
fi

# If relative path is used prepend a ./
tail=`echo $progname | sed 's/\/.*//'` 
if  [ "$tail" != "" ]; then
  progname="./$progname"
fi

# Execute the program
$progname
exit 0

