# $Id: makefile,v 1.1.6.1 2002/04/24 03:25:29 erik Exp $ 

DIRS     = BasicUtil Machine Log Error TimeMgmt Timer App mpiuni
LOCDIR   = src/Infrastructure

include ${ESMF_DIR}/build/${ESMF_ARCH}/base









